# Рабочая тетрадь №2. Библтотеки
###  %USERNAME%
## Библиотека NumPy
&emsp;&emsp;NumPy (__Num__erical__Py__thon) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.  
&emsp;&emsp;Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:  

- _pip install numpy_  

&emsp;&emsp;Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:  

- _import numpy as np_  

&emsp;&emsp;Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.  
&emsp;&emsp;Наиболее важные атрибуты объектов ndarray:  
- __ndarray.ndim__ - число измерений (чаще их называют "оси") массива.  
- __ndarray.shape__ - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.  
- __ndarray.size__ - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
- __ndarray.dtype__ - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
- __ndarray.itemsize__ - размер каждого элемента массива в байтах.
- __ndarray.data__ - буфер, содержащий фактические элементы массива. 

Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.  
&emsp;&emsp;Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

### 1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация
начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
Задача:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами
3. Создать вектор размера 10, заполненный заданным числом
4. Создать вектор со значениями от 10 до 49

In [2]:
import numpy as np
a = np.zeros(10)
b = np.ones(10)
c = np.full(10,5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример
Задача:
Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение

In [3]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin,Zmax,Zmean)

0.02705795109349307 0.9762266410391879 0.5083689877845771


### 1.2.4 Пример
Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами

In [4]:
import numpy as np
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Задача:
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [5]:
import numpy as np
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Задача:
Отсортировать массив

In [6]:
import numpy as np
arr = np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами

In [7]:
import numpy as np
x = np.full((8, 8),0)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1: x[i, j] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.


In [8]:
import numpy as np
b = np.full((5, 5), 1).reshape(5, 5) * np.arange(5)
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [9]:
import numpy as np
x = np.random.randint(10, size=(3, 3, 3))
print(x)

[[[6 1 7]
  [9 3 7]
  [7 5 2]]

 [[8 5 9]
  [3 9 6]
  [8 0 3]]

 [[9 3 2]
  [3 1 4]
  [5 9 8]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [10]:
import numpy as np
x = np.full((10, 10), 1)
x[1:-1, 1:-1] = 0
        
print(x)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [11]:
import numpy as np
x = np.random.randint(10, size=(3, 3))
print(-np.sort(-x))

[[6 6 4]
 [7 7 2]
 [8 8 2]]


### 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.


In [12]:
import numpy as np
x = np.ones((10, 10))
print(x.size)
print(x.shape)
print(x.ndim)

100
(10, 10)
2


## Библиотека Pandas
&emsp;&emsp;Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких источников.  
&emsp;&emsp;_Библиотека pandas_ – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то _pandas_ – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.  
&emsp;&emsp;_Библиотека pandas_ присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:  
- pip install pandas  

&emsp;&emsp;Для импорта библиотеки используйте команду: import pandas as pd Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.  
&emsp;&emsp;__Series__ – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.  
&emsp;&emsp;__DataFrame__ – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

### 2.2.1 Пример
Задача:
Создать Series из списка Python, словаря Python, и массива Numpy
(установить буквенные метки для последнего).

In [13]:
import pandas as pd
lst = [1,2,3,4,5]
d = {'a':1,'b':2,'c':3}
ndarr = np.array([1,2,3,4,5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### 2.2.2 Пример
Задача:
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [14]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5], ['a','b','c','d','e'])
s2 = pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[1:])

1
5
1    4
2    3
3    2
4    1
dtype: int64


### 2.2.3 Пример
Задача:
Создайте новый фрейм данных.

In [15]:
import pandas as pd
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст'] = [38,25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
Задача:
Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/tit
anic.csv

In [16]:
import pandas as pd
# Создать URL-адрес
url = "https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv"
dataframe = pd.read_csv(url)
# показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

### 2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.

In [17]:
import pandas as pd
import numpy as np
a = pd.Series([1, 2, 7])
b = pd.Series([9, 4, 3])
c = 0
for i in range(len(a)):
    c += (a[i] - b[i]) ** 2
print(np.sqrt(c))

9.16515138991168


### 2.2.5 Пример
Задача:
Пронализировать характеристики фрейма данных

Решение:

Одна из самых простых вещей, которые мы можем сделать после
загрузки данных, – это взглянуть на первые несколько строк с
помощью метода head. На последние строки можно посмотреть с
помощью функции tail. Мы также можем взглянуть на количество
строк и столбцов: dataframe.shape. Кроме того, используя метод
describe, мы можем получить описательную статистику для любых
числовых столбцов.

In [18]:
import pandas as pd
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [28]:
dataframe["Age"].median()
dataframe["Age"] = dataframe["Age"].fillna(28)
dataframe.describe()

Age     Survived      SexCode
count  1313.000000  1313.000000  1313.000000
mean     29.380716     0.342727     0.351866
std      10.881539     0.474802     0.477734
min       0.170000     0.000000     0.000000
25%      26.000000     0.000000     0.000000
50%      28.000000     0.000000     0.000000
75%      30.000000     1.000000     1.000000
max      71.000000     1.000000     1.000000

In [34]:
import pandas as pd
from sklearn import preprocessing
x = np.array([[21], [22], [23], [24], [20]])
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scalerZ = scaler.fit_transform(x)
scalerZ

array([[0.25],
       [0.5 ],
       [0.75],
       [1.  ],
       [0.  ]])

In [35]:
import pandas as pd
from sklearn import preprocessing
x = np.array([[21], [22], [23], [24], [20]])
scaler = preprocessing.StandardScaler()
scalerZ = scaler.fit_transform(x)
scalerZ

array([[-0.70710678],
       [ 0.        ],
       [ 0.70710678],
       [ 1.41421356],
       [-1.41421356]])

### 2.2.6 Пример

Задача:
Выберите индивидуальные данные или срезы фрейма данных.
Решение:
Для выбора одной или нескольких строк либо значений использовать
методы 1ос или iloc

In [19]:
import pandas as pd
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

### 2.2.7 Пример

Задача:
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из
пассажиров первого класса.

In [20]:
import pandas as pd
dataframe = pd.read_csv('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv')
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

### 2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из 
него фрейм данных (например, коллекцию фреймов данных можно 
найти здесь: https://github.com/akmand/datasets).

In [21]:
import pandas as pd
x = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/main/birdkeeper_lungcancer.csv")
x.head(5)

fm    ss      bk  ag  yr  cd          lc
0  Male   Low    Bird  37  19  12  LungCancer
1  Male   Low    Bird  41  22  15  LungCancer
2  Male  High  NoBird  43  19  15  LungCancer
3  Male   Low    Bird  46  24  15  LungCancer
4  Male   Low    Bird  49  31  20  LungCancer

### 2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных 
те же действия, что и в примерах 2.2.5-2.2.7.

In [22]:
import pandas as pd
x = pd.read_csv("https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv")
x.head(5)
x.tail(2)
x.shape
x.describe()

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

## Работа с числовыми данными
&emsp;&emsp;Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж).  
&emsp;&emsp;___Нормализация данных___ — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.  
&emsp;&emsp;Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.  
&emsp;&emsp;На практике наиболее распространены следующие методы нормализации признаков:  
- ___Минимакс___ – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
- ___Z-масштабирование___ данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.

### 3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [23]:
import pandas as pd
from sklearn import preprocessing
x = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")
scaler = preprocessing.MinMaxScaler(feature_range=(0, 1))
scalerZ = preprocessing.StandardScaler()
x[["sepal_length_cm"]] = scaler.fit_transform(x[["sepal_length_cm"]])
x[["sepal_width_cm"]] = scalerZ.fit_transform(x[["sepal_width_cm"]])
x

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]